### PR TITLE
Feature: Click on logo redirects to coronwarn.app (Closes #9)

### LINKED ISSUE #9: Logo should redirect to coronawarn.app
## Feature description

When clicking on the logo in the top left corner or in the footer it would be nice if the main page www.coronawarn.app would be opened.

## Problem and motivation
Users who want to find out more about the Corona-Warn-App maybe return to this page while waiting for their download to be finished. Then it would be nice if they could directly go to the main page via the logo.

## Is this something you're interested in working on

I'd like to but not sure yet wether I'm able to.

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR adds the feature that a click on the logo either in the header or in the footer links to the https://coronawarn.app page in the corresponding language.

Since I'm really no expert in html, please review these changes and feel free to make the implementation more robust by adding commits. 

---

Closes #9

### CODE REVIEW

**Comment by Ein-Tim** [comment]
Could be that this PR broke some links. Investigating.

**Comment by christianneu** [comment]
Thanks @Ein-Tim for your contribution. I will merge it into main.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks!

**Comment by svengabr** [comment]
Thanks @Ein-Tim !

**Pull request merged**
