### PR TITLE
Update documentation in README (No automatic deployment)

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR updates the documentation reg. updating the landing pages. 

Feedback is welcome!

### CODE REVIEW

**Review by svengabr — APPROVED** [review]

**Comment by svengabr** [comment]
Thanks @Ein-Tim, the information regarding automatic deployments was infact, wrong.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I don't normally follow PRs on this site, so I didn't notice a typo before this was merged. If you are going to make changes I also have some suggestions for the grammar and formatting in addition to the one typo:

"Deploying of the chnages" => 
"Deployment of changes" 

"Thus, even if a PR is merged into `main` here on GitHub , the change is not immediately visible on the pages, but only after the change was deployed."

=>

"Thus, even if a PR is merged into `main` here on GitHub, changes are not immediately visible on the pages, but only after the changes have been deployed."

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks, I should've pinged you! 😅 

I will provide a PR implementing your suggested changes & ping you so you can take a look. Thanks for the feedback!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I have subscribed to PRs from here now, so no need to ping me. I will get notified automatically.

**Comment by Ein-Tim** [comment]
That's even better 😄

**Comment by Ein-Tim** [comment]
PR: https://github.com/corona-warn-app/cwa-event-landingpage/pull/41

**Pull request merged**
