### PR TITLE
Update footer to align with coronawarn.app

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description

This PR updates the footer to match the one from coronawarn.app.

## What was changed?

The file `global.json` which includes the settings for the footer.

## Screenshots

| DE | EN |
|---|---|
| Bildschirmfoto 2022-07-24 um 11 52 30 | Bildschirmfoto 2022-07-24 um 11 52 38 |

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The https://www.coronawarn.app/en/accessibility/ page only refers to the website [www.coronawarn.app](https://www.coronawarn.app).

The section of the README [About this Repository](https://github.com/corona-warn-app/cwa-event-landingpage#about-this-repository) says:

"This repository contains the source files of the official Corona-Warn-App landing page as it is available at [e.coronawarn.app](https://e.coronawarn.app) (for event-registration),[s.coronawarn.app](https://s.coronawarn.app) (for rapid antigen tests) & [p.coronawarn.app](https://p.coronawarn.app) (for rapid PCR tests)."

So there is no overlap between the Accessibility Statement URL coverage ([www.coronawarn.app](https://www.coronawarn.app)) and the URLs controlled by this repository ( [e.coronawarn.app](https://e.coronawarn.app), [s.coronawarn.app](https://s.coronawarn.app) & [p.coronawarn.app](https://p.coronawarn.app)).

It would not be harmful to add the links in this PR, however I don't think it would be helpful.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

AFAIK the intention was to always keep the footer of the two pages aligned.

**Comment by svengabr** [comment]
LGTM

**Review by svengabr — APPROVED** [review]

**Comment by Ein-Tim** [comment]
@MikeMcC399 Very strange. I took the screenshots of this PR on my environment using the build instructions from this repositories README. I did not encounter the problem [you described](https://github.com/corona-warn-app/cwa-event-landingpage/pull/67#issuecomment-1409328678), and which is visible on both your local environment and the Vercel preview deployment, when taking the screenshots. Any idea what's wrong here?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> Any idea what's wrong here?

The site was never converted to be accessible and the code is missing.

In https://github.com/corona-warn-app/cwa-event-landingpage/issues/68#issuecomment-1409788189 I go into more detail and suggest to revert this PR.

**Pull request merged**
