### PR TITLE
Update footer to align it with the one from coronawarn.app

### PR DESCRIPTION
**Pull request by Ein-Tim**
Align footer with the one from coronawarn.app.

PRs in the https://github.com/corona-warn-app/cwa-website repository:

- https://github.com/corona-warn-app/cwa-website/pull/1452 from @MikeMcC399
- https://github.com/corona-warn-app/cwa-website/pull/1455 from @Ein-Tim

Preview of the changes:

Bildschirmfoto 2021-07-03 um 17 59 14

### CODE REVIEW

**Comment by Ein-Tim** [comment]
@dsarkar Could you take a look at this, please?

**Review by dsarkar — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Is this for https://s.coronawarn.app/ or which URL(s) will it change?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

It changes https://s.coronawarn.app as well as https://e.coronawarn.app.

**Comment by Ein-Tim** [comment]
@dsarkar 

Is there something still blocking this merge?

**Comment by Ein-Tim** [comment]
This PR is open for ca. 3 months now and it has been approved by @dsarkar, but it still hasn't been merged. Please give a reason why this can't be merged at the moment or merge it. 

Thank you.

**Comment by dsarkar** [comment]
@Ein-Tim Snowed under ... Thanks!

**Pull request merged**
